services:
  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: nlqdb-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ../backend/.env
    volumes:
      - ../backend/src:/app/src
    networks:
      - nlqdb-network

  # Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: development
    container_name: nlqdb-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=https://symmetrical-spoon-69vq4746p7pq2rqqg-5000.app.github.dev/api
    depends_on:
      - backend
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
      - ../frontend/.env:/app/.env
    networks:
      - nlqdb-network

networks:
  nlqdb-network:
    driver: bridge
